sudo: false
language: node_js
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'

addons:
  apt:
    packages:
      - php5
      - php5-cgi

before_install:
  - php-cgi --version

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
