# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

version: "{build}"

environment:
  matrix:
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "7"
      platform: x86
    - nodejs_version: "8"
      platform: x86

install:
  - cinst -y php -i
  - SET PATH=C:\tools\php72\;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build: off

matrix:
  fast_finish: true

test_script:
  - node --version && npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

cache:
  - 'node_modules -> appveyor.yml,package.json,package-lock.json'
