# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "stable"

install:
  - cinst php
  - SET PATH=C:\tools\php\;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - npm update -g npm
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm\node_modules -> package.json'    # global npm modules
  - '%APPDATA%\npm-cache -> package.json'           # npm cache
  - 'node_modules -> package.json'                  # local npm modules
